version: 0.2

env:
  variables:
    PACKAGE_NAME: "compare-diarization"
    BUILD_TIMESTAMP: "$(date +%Y-%m-%d_%H-%M-%S)"

phases:

  install:
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - nvidia-smi
      
      - apt-get -qq update
      - uname -a 

      - apt-get install -y cmake curl unzip ffmpeg git mpg123
      - apt-get install -y python3 python3-pip git

      - cmake --version
      - git --version
      
      # replace the github with Oauth token login information in the URL.
      - git config --global url."https://oauth2:${GHAPI}@github.com/".insteadOf "https://github.com/"
   
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install 1> /dev/null
      - aws --version

      - echo "Checking environment"
      - echo ${API_TOKEN}
      - echo $CODEBUILD_SOURCE_REPO_URL

      - apt-get -qq -o=Dpkg::Use-Pty=0 -y install python3-pip 1> /dev/null
      - python3 --version
      - pip install --no-cache -r requirements.txt


  build:
    commands:
      - set -e # stop build if errors
      - echo "Running models ..."
      - python3 -m src.main
      - find . -maxdepth 2 -type d -ls -name aws -prune

artifacts:
  files:
    - 'out/*'
  discard-paths: no
